export let data = [
{name: "unfinity-extras-helper", 
  lastUpdate: "Feb 5, 2024", 
  description: "A webapp for helping users manage certain Unfinity cards from Magic: The Gathering",
  technologies: ["Vite", "JavaScript", "Tailwind CSS", "Node", "React Router", "React", "HTML", "CSS"],
  imageURL: "../images/unfinityImage.png",
  githubURL: "https://github.com/andy9299/unfinity-extras-helper",
  deploymentURL: "https://andy9299.github.io/unfinity-extras-helper/"
},
{name: "portfolio", 
  lastUpdate: "Feb 5, 2024", 
  description: "My portfolio site! I tried using new technologies to get introduced to it. Though some I used very lightly, but if I add more stuff surely I'll get to it!",
  technologies: ["Vite", "TypeScript", "Tailwind CSS", "DaisyUI", "Node", "React", "HTML", "CSS"],
  imageURL: "../images/portfolioImage.png",
  githubURL: "https://github.com/andy9299/portfolio",
  deploymentURL: "https://andy9299.github.io/portfolio"
},
{name: "jp-trainer",
lastUpdate: "Oct 23, 2023",
description: "The final project for my bootcamp Springboard. A site to help users memorize Japanese characters. Users can also create an account to create custom lists. I made it in order to motivate me to learn Japanese.",
technologies: ["PostgreSQL", "Node", "Express", "React", "React-Router", "bootstrap", "Axios", "Supertest", "HTML", "CSS", "Javascript"],
imageURL: "../images/jptrainerImage.png",
githubURL: "https://github.com/andy9299/jp-trainer",
  deploymentURL: "https://jp-trainer.surge.sh/"
},
 {name: "AniCharaBot",
lastUpdate: "Oct 14, 2023",
description: "A small bot for Discord where a user can get information about anime characters from the AniListAPI or play a small guessing game.",
technologies: ["Discord.js", "GraphQL", "Node", "Javascript"],
imageURL: "../images/anicharabotImage.png",
githubURL: "https://github.com/andy9299/AniCharaBot",
},
 {name: "seiyuulist",
lastUpdate: "May 3, 2023",
description: "The first captsone for my bootcamp Springboard. A site where users can get information about seiyuu (JP voice actor/actress) or create an account and create their own seiyuu ranking.",
technologies: ["Python", "Flask", "HTML", "CSS", "bootstrap", "Javascript"],
imageURL: "../images/seiyuulistImage.png",
githubURL: "https://github.com/andy9299/seiyuulist",
},
];
